name: Docker Image CI

on:
  push:
    branches:
    - feature/*
  pull_request:
    branches:
    - main
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_NAME:latest

    - name: Push Image
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker push $IMAGE_NAME:latest